name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
    - name: Build the Docker image
      run: docker build -t farhan0212/smartweb:latest .
      
    - name: Push Docker image
      run: docker push farhan0212/smartweb:latest

    - name: Action SSH
      id: action-ssh
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.VPS_HOST }} 
        username: ${{ secrets.VPS_USERNAME }} 
        key: ${{ secrets.VPS_SSH_KEY }} 
        passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
        script: 'bash /scripts/deployment.sh'

